server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:

        - id: carModule
          uri: http://localhost:8891/carrinho
          predicates:
            - Path=/**
        - id: prodModule
          uri: http://localhost:8889/produto
          predicates:
              - Path=/**
        - id: userModule
          uri: http://localhost:8890/usuario
          predicates:
             - Path=/**
  application:
    name: API-GATEWAY-PORTEIRO
