

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: API-GATEWAY-PORTEIRO
  cloud:
    gateway:
      routes:
        - id: carModule
          uri: lb://carrinho
          predicates:
            - Path=/car/**
        - id: prodModule
            uri: lb://produto
            predicates:
              - Path=/prod/**
        - id: userModule
            uri: lb://usuario
            predicates:
              - Path=/user/**
