spring:
  application:
    name: usuario
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:file:./data/exemplo
      username: sa
      password:
      driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

server:
  port: 8890

  eureka:
    client:
      serviceUrl:
        defaultZone: ${vcap.services.eureka-service.credentials.uri:http://192.168.0.102:8761}/eureka/




